version: "3.9"
services:
  web:
    restart: always
    image: costi-online
    ports:
      - "82:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: costi_online
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"