version: "3.8"
services:
  web:
    build: .
    restart: always
    image: costi-online
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: costi_online
      MYSQL_USER: cow
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"