package com.costi.csw9.Util;

import com.costi.csw9.Model.Ajax.MediaInfo;
import com.costi.csw9.Model.Ajax.ProjectInfo;

import javax.print.attribute.standard.Media;
import java.util.ArrayList;
import java.util.List;

public class InfoInitializer {
    public static List<ProjectInfo> initializeProjects() {
        List<ProjectInfo> objects = new ArrayList<>();

        // Create objects
        objects.add(new ProjectInfo("interdimensional", "python", "", "/images/webpageImages/CS-122.png", "Computer Science 122 Projects", true, "School Collaborative Projects | 2022",  "These are a collection of Python projects I have made for my Python class in SJSU most of these are projects I have collaborated with. The GitHub repositories listed here may not contain the final code we used to turn in, as there were some syncing issues with our code. Some highlights of the class were using tkinter to make a matching game and a simple web server using django and flask.", new String[]{"https://github.com/CKhamis/CS-122-Homework-2", "https://github.com/CKhamis/CS-122-Homework-4", "https://github.com/CKhamis/CS-122-Homework-6", "https://github.com/CKhamis/CS-122-Homework-7", "https://github.com/CKhamis/CS-122-Homework-8"}));
        objects.add(new ProjectInfo("interdimensional", "java", "", "/images/webpageImages/CostiOnline.jpg", "Costi Online", false, "Personal Project | 2022", "Costi Online is a website that is designed to show off various projects, services, and media I made. This project initially began as a website that covers my 9th Minecraft survival world. It had links to participate in elections, polls, and the history of the previous worlds. After it was published on costionline.com, I decided to make it more general. The aforementioned feature has been moved to the <a href=\"/Minecraft\">Minecraft</a> section.", new String[]{"https://github.com/CKhamis/Costi-Online-Website"}));
        objects.add(new ProjectInfo("interdimensional", "java", "CIPolarium", "/images/webpageImages/Polarium.png", "Constantine [IN]GRID Polarium", true, "Personal Project | 2021", "This is a personal project I made that keeps track of various relationships I have made similar to a journal. I used Java Spring and Hibernate for this project, much like Costi Online. This project was discontinued because of complications with making a secure account system (which is very important for a personal journaling program). This program was able to add, edit, and remove people. Each person had their own database for tracking events.", new String[]{"https://github.com/CKhamis/Constantine-INGRID-Polarium"}));
        objects.add(new ProjectInfo("interdimensional", "java", "CNGrid", "/images/webpageImages/NextGrid.jpg", "Constantine [NEXT]GRID", true, "Private Repository | 2021", "This project was quite similar to [IN]GRID Polarium in terms of purpose. They both were designed to be a personal diary. However, this project used Java Swing as its interface and used CSV files for data persistence. There were no third party libraries used in this program, so I made my own CSV reader and writer classes myself. The project was discontinued due to frustrations with Java Swing and persistent bugs and limitations with displaying information. The GitHub repository is private because it contains a CSV file with personal information.", new String[]{}));
        objects.add(new ProjectInfo("interdimensional", "java", "", "/images/webpageImages/BankingApp.png", "Banking App", true, "School Collaborative Project | 2021", "\"Our banking app was created using the Java Swing library and an MVC pattern with event driven programming. The application allows for multiple users. Each user has their own account and have different bank accounts such as checkings and savings. The user is able to withdraw, deposit, and transfer to and from each account. In addition, the user has a Credit account where they can view thier credit card balance and pay off their credit card bill.\" - Sunny Chen, a collaborator", new String[]{"https://github.com/CKhamis/banking-app"}));
        objects.add(new ProjectInfo("pseudo-industrial", "java", "", "/images/webpageImages/SCQG.jpg", "Smart Console Query Generator", true, "Personal Project | 2020", "This project was made to help me automate a frequently repeating task of my job as an intern in the Cyber Security team of San Jose. This project was meant to create queries for the CheckPoint Smart Console application.", new String[]{"https://github.com/CKhamis/SmartConsoleQueryGenerator"}));
        objects.add(new ProjectInfo("pseudo-industrial", "java", "", "/images/webpageImages/Polaric.jpg", "Constantine [IN]GRID Polaric", true, "Private Repository | 2020", "This was an application designed to analyze spreadsheet journals. It could recognize different versions of the CSV files and show you differences between them, analyze the data in them so you can make better decisions, and more. It was quite an advanced program that took a few months to develop. The project was discontinued because I did not know how to make a GUI for it. This project contains personal information, so the repository is private.", new String[]{}));
        objects.add(new ProjectInfo("pseudo-industrial", "java", "", "/images/webpageImages/FGSA.jpg", "Five Guys Schedule Analyzer", true, "Personal Project | 2020", "This project was meant to take schedules I receive from Five Guys as an input and give me helpful analytical information. It used my CSV reader file to analyze each schedule and locate valuable information. Discontinued because I did not know of any good way of making a GUI.", new String[]{"https://github.com/CKhamis/Five-Guys-Schedule-Analyzer"}));
        objects.add(new ProjectInfo("pseudo-industrial", "web", "CIPolaris", "/images/webpageImages/Polaris.jpg", "Constantine [IN]GRID Polaris", true, "Personal Project | 2019", "This project was mainly developed using Javascript D3.js to populate data on webpages from CSV files. The purpose of this program is quite similar to what came after it, which is to display journaling information. The project was discontinued because I could not figure out how I would turn this into a functioning server in the long run. There are no public repositories for this project because the CSV it uses contains personal information.", new String[]{}));
        objects.add(new ProjectInfo("pseudo-industrial", "web", "", "/images/webpageImages/CostiInc.jpg", "Costi Inc.", true, "Personal Project | 2018", "This project is a website I made in 2018 that shared a very similar purpose to this website. It featured the different projects and video channels I was posting to at the time. It utilized bootstrap and was hand coded by me.", new String[]{"https://github.com/CKhamis/Costi-Inc"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/CR.jpg", "Costi Resume", true, "Personal Project | 2017", "Codename project Velocity. This is a resume website I made using HTML, CSS, and JavaScript. I was about 15 or 16 when I made this. I made this during the time I was learning D3.js", new String[]{"https://github.com/CKhamis/Resume-Website"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/InfiniteID.jpg", "Constantine Infinite ID", true, "Personal Project | 2017", "This was the first diary/journaling program I created for myself. It was a website that used D3.JS to pull information from a CSV file that contained all the information needed. The project was discontinued due to bugs that I could not remove at the time.", new String[]{"https://github.com/CKhamis/Infinite-ID"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/RoboticsWebsite3.png", "Pioneer Robotics Team Website (Milestone 3)", true, "Club Project | 2017", "This was a new project I wanted to make for my robotics team. I built it from scratch and I wanted to avoid the design misdirections its predecessors have taken (because of my team manager's preferences) while also applying feedback I heard about the current website. This website is unfinished because during its initial development, my team's manager suggested I should use a website builder instead. Knowing the countless hours and energy I put into this project (and previous robotics webpages) I quit.", new String[]{"https://github.com/CKhamis/https-github.com-CKhamis-Robotics-Website-Milestone-3"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/RoboticsWebsite2.png", "Pioneer Robotics Team Website (Milestone 2)", true, "Club Project | 2017", "This was an iteration of the previous milestone 1 robotics page. It had more features, simpler and easier to navigate pages, and more Java Script integration. It even featured the game snake on the 404 page. It was seemingly generally liked among my team.", new String[]{"https://github.com/CKhamis/Robotics-Website-Milestone-2"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/RoboticsWebsite.jpg", "Pioneer Robotics Team Website (Milestone 1)", true, "Club Project | 2016", "After making a handful of websites for my robotics team (each being rejected at their final development stages) I decided to have the team manager chose what elements he wanted in the team website. He ended up choosing this website design, which was not great in my personal opinion, but I was able to get this published. I made all the assets that went into this website and hand coded everything.", new String[]{"https://github.com/CKhamis/Resume-Website"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/Acceleration.png", "Pioneer Robotics Team Website (Codename: Acceleration)", true, "Club Project | 2015", "This was a website I made over the summer 2015 break in my freshman year. I created a colorful, eye-catching website for my robotics team. I made it entirely from HTML and CSS, created my own assets, and designed the layout myself. I do not have a backup of this project unfortunately and this screenshot is all I have of it. This project was promptly rejected during the first week of school.", new String[]{}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/MWC.jpg", "Pioneer Robotics Team Mobile Website C", true, "Club Project | 2015", "At the time, I was very proud of what I have made. I created a more consistent interface, invented the idea of team skill \"categories,\" with their own individual informative webpages, and displayed all information on our desktop website in a mobile friendly way. This was before I learned bootstrap well. This is not the final version of the project, as I distinctly remember placing JavaScript Easter eggs which are not present in the version I uploaded.", new String[]{"https://github.com/CKhamis/Robotics-Mobile-Website-C"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/RoboticsMobileWebsite.jpg", "Pioneer Robotics Team Mobile Website", true, "Club Project | 2015", "When I joined my high school robotics team, I was asked by my web captain to create a mobile counterpart to our desktop only site. I eventually came up with this project. It featured javascript easter eggs and phone-specific styling. I used only HTML, CSS, and Java Script to create my project without any frameworks. The version pictured and saved to GitHub is a very early version of the project. I had since made other versions that look completely different.", new String[]{"https://github.com/CKhamis/Robotics-Mobile-Website"}));
        objects.add(new ProjectInfo("childhood", "web", "", "/images/webpageImages/Birds.jpg", "Original Angry Birds Wiki", true, "Personal Project | 2014", "This project is a website dedicated to the topic of Angry Birds, a game I liked when I was little. I hand coded this entire website using HTML and CSS with no frameworks.", new String[]{"https://github.com/CKhamis/Angrybird-Wiki"}));
        objects.add(new ProjectInfo("childhood", "web", "", "/images/webpageImages/OriginalCostiWebsite.jpg", "Original Laptoop Website", true, "Personal Project | 2013", "I made this website when I was first learning web development in 2013. At the time, I was 12. This website featured a product page for a made up laptop of the made up brand \"laptoop,\" which I came up with in third grade.", new String[]{"https://github.com/CKhamis/Laptoop-Company-Website"}));
        return objects;
    }

    public static List<MediaInfo> initializeMedia(){
        List<MediaInfo> media = new ArrayList<>();

        // 2022
        media.add(new MediaInfo("2022", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/LYXEK4cTHag\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>", "Flea Market Finds: Episode 2", "Adobe Premiere Pro | 2022", "Join Alex, Costi, Jack & Haydon in gathering the highest quality of finds at Capitol flea market! Although not perfect, this video uses enhanced editing techniques over the previous installment in the series.", "https://youtu.be/LYXEK4cTHag"));
        media.add(new MediaInfo("2022", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/5c5guItHIc4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>", "Flea Market Finds: Episode 1", "Adobe Premiere Pro | 2022", "Flea Market finds is the newest video series in my collection. Flea market finds is about what Haydon, me, and sometimes a special guest, find in flea markets. We both aim to collect electronics at cheap prices. In this episode, we go to Flea Market Capitol.", "https://youtu.be/5c5guItHIc4"));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV RH.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Rose Herrera\">", "JK CS Testimonial Video: Rose Herrera", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video completely by myself at Rose Herrera's house. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV CM.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Carol Marques\">", "JK CS Testimonial Video: Carol Marques", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent the raw version of this video, so I only participated in editing. I made sure to use practical and clear animations. I as asked to make this video in a landscape orientation, so I added filled the background with a blurry and enlarged version of the original video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV FT.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Fred Tovar\">", "JK CS Testimonial Video: Fred Tovar", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent the raw version of this video, so I only participated in editing. I made sure to use practical and clear animations. I as asked to make this video in a landscape orientation, so I added filled the background with a blurry and enlarged version of the original video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV RH O.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Rose Herrera\">", "JK CS Testimonial Video: Rose Herrera (Original)", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent the raw version of this video, so I only participated in editing. I made sure to use practical and clear animations. I as asked to make this video in a landscape orientation, so I added filled the background with a blurry and enlarged version of the original video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV JM.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: John McKay\">", "JK CS Testimonial Video: John McKay", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video myself at a major supporters' event. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV ML.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Marby Lee\">", "JK CS Testimonial Video: Marby Lee", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video myself at a major supporters' event. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV KJ.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Kevin Jensen\">", "JK CS Testimonial Video: Kevin Jensen", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video myself at a major supporters' event. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV MW.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Mike Wasserman\">", "JK CS Testimonial Video: Mike Wasserman", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video myself at a major supporters' event. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JK CS Ad 2.jpg\" class=\"card-img-top\" alt=\"Johnny Khamis for County Supervisor Ad 2\">", "Johnny Khamis for County Supervisor Ad 2", "Adobe Premiere Pro | 2022", "At my dad's campaign supporters' party, I filmed a short video ad featuring him. I made sure to use my new audio equipment to better capture his voice over the background noise. I also reused some assets from previous videos, as their purposes were very similar.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV PF.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Pam Foley\">", "JK CS Testimonial Video: Pam Foley", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video, and I was asked to handle all the editing for it. I made sure to use practical and clear animations. I as asked to make this video in a landscape orientation, so I added filled the background with a blurry and enlarged version of the original video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV TH.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Tim Herlihy\">", "JK CS Testimonial Video: Tim Herlihy", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video and I was asked to handle all the editing for it. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV SS.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Scot Smithee\">", "JK CS Testimonial Video: Scot Smithee", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video and I was asked to handle all the editing for it. I made sure to use practical and clear animations. At this point, I continued using the same assets I have created with the first video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV TN.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Tam Nguyen\">", "JK CS Testimonial Video: Tam Nguyen", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video and I was asked to handle all the editing for it. I made sure to use practical and clear animations. I was also asked to provide English subtitles for the video, which I included as well.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV LD.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Lan Diep\">", "JK CS Testimonial Video: Lan Diep", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video and I was asked to handle all the editing for it. I made sure to use practical and clear animations. I was also asked to provide English subtitles for the video, which I included as well.\n", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV LM.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor YouTube Short Ad 2\">", "JK County Supervisor YouTube Short Ad 2", "Adobe Premiere Pro | 2022", "This was a video edited by myself and filmed by a third party that was shortened down as much as possible to fit into a YouTube 6-second ad. This video was shot in portrait, so I modified all my existing assets to work with it.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV NS.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor YouTube Short Ad 1\">", "JK County Supervisor YouTube Short Ad 1", "Adobe Premiere Pro | 2022", "This was a video edited by myself and filmed by a third party that was shortened down as much as possible to fit into a YouTube 6-second ad. This video was shot in portrait, so I modified all my existing assets to work with it.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV BH.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Bill Hubka\">", "JK CS Testimonial Video: Bill Hubka", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV LL.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Liz Lawler\">", "JK CS Testimonial Video: Liz Lawler", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV LC.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Larry Carr\">", "JK CS Testimonial Video: Larry Carr", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV DD.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Dev Davis\">", "JK CS Testimonial Video: Dev Davis", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV SL.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Sam Liccardo\">", "JK CS Testimonial Video: Sam Liccardo", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV MB.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Marie Blankley\">", "JK CS Testimonial Video: Marie Blankley", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV DG.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Don Gage\">", "JK CS Testimonial Video: Don Gage", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV DD.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Dev Davis\">", "JK CS Testimonial Video: Dev Davis", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV DK.jpg\" class=\"card-img-top\" alt=\"Dave Knopf\">", "JK CS Testimonial Video: Dave Knopf", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Homelessness.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor Homelessness Ad\">", "JK County Supervisor Homelessness Ad", "Adobe Premiere Pro | 2022", "This was the first video ad I created myself for my dad's political campaign. We used my dad's phone to film this video because of its portability. Since the video was filmed in the same spot as the previous, my editing techniques did not change.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Safety.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor Safety Ad\">", "JK County Supervisor Safety Ad", "Adobe Premiere Pro | 2022", "This was the first video ad I created myself for my dad's political campaign. We used my dad's phone to film this video because of its portability. This video was about safety in the county. I needed to use my video editing skills to quicken the video.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Parks.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor Parks Ad\">", "JK County Supervisor Parks Ad", "Adobe Premiere Pro | 2022", "This was the first video ad I created myself for my dad's political campaign. We used my dad's phone to film this video because of its portability. This video was about protecting the environment and open spaces in the county. Heavy noise reduction was needed because it was windy", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Lightrail.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor Lightrail Ad\">", "JK County Supervisor Lightrail Ad", "Adobe Premiere Pro | 2022", "This was the first video ad I created myself for my dad's political campaign. We used my dad's phone to film this video because of its portability. I used my skills in video editing to remove audio noise, stabilize the video, add effects, and display the logo.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Ad 1.jpg\" class=\"card-img-top\" alt=\"Johnny Khamis County Supervisor Commercial 1\">", "Johnny Khamis County Supervisor Commercial 1", "Adobe Premiere Pro | 2022", "This was a video that I was asked to modify that was originally created by a hired third party. I was asked to edit some text, add the logo, and other small fixes.", ""));

        //2021
        media.add(new MediaInfo("2021", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/xpnTFsiiA_0\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Memory Slideshow: Summer 2021", "Adobe Premiere Pro | 2021", "As the title suggests, this is a montage of the best memories I had in my summer 2021. This isn't the first video in the memory montage series, and certainly not the last. Although there is not enough Minecraft here!", ""));

        //2020
        media.add(new MediaInfo("2020", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/OlB1ILARBxE\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Memory Slideshow: SJSU 2019", "Adobe Premiere Pro | 2020", "This video highlighted my first semester and a half at SJSU. The selfies I took were part of a school project, so don't judge \uD83D\uDE24", "https://youtu.be/OlB1ILARBxE"));
        media.add(new MediaInfo("2020", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/jDfV5RQrKlU\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Memory Slideshow: Summer 2019", "Adobe Premiere Pro | 2020", "This is the second memory montage in the series about my summer in 2019", "https://youtu.be/jDfV5RQrKlU"));
        media.add(new MediaInfo("2020", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/Oc8686Xw7vg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Memory Slideshow: Pioneer 2019", "Adobe Premiere Pro | 2020", "Bored and stuck at home with nothing to film, I decided to begin a series of compilations that would help me remember the good times. This was the first in the series. It was about my time in high school.", "https://youtu.be/Oc8686Xw7vg"));
        media.add(new MediaInfo("2020", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/blxsL72ZpT4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "PPAP", "Adobe Premiere Pro | 2020", "Filmed in 2016, this video was a parody of the infamous PPAP video that was popular at the time. This project was never edited because I thought it was cringy at the time, which was exactly why I edited it in 2020. This is the last Costi Entertainment branded video. The editing used here is far better than what I made in 2016, which is a good indicator of the progression of my skill.", "https://youtu.be/blxsL72ZpT4"));
        media.add(new MediaInfo("2020", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/phRo1lOsNts\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Costi Entertainment Intro 2020", "Adobe Premiere Pro | 2020", "This was the last Costi Entertainment intro I made. Not knowing what was going to happen next, I had big plans for 2020. I made this intro video, but it was only used in 1 video.", "https://youtu.be/phRo1lOsNts"));

        //2019
        media.add(new MediaInfo("2020", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV KJ.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Kevin Jensen\">", "JK CS Testimonial Video: Kevin Jensen", "Adobe Premiere Pro | 2022", "", ""));

        return media;
    }
}
