package com.costi.csw9.Util;

import com.costi.csw9.Model.Ajax.MediaInfo;
import com.costi.csw9.Model.Ajax.ProjectInfo;

import javax.print.attribute.standard.Media;
import java.util.ArrayList;
import java.util.List;

public class InfoInitializer {
    public static List<ProjectInfo> initializeProjects() {
        List<ProjectInfo> objects = new ArrayList<>();

        // Create objects
        objects.add(new ProjectInfo("interdimensional", "python", "", "/images/webpageImages/CS-122.png", "Computer Science 122 Projects", true, "School Collaborative Projects | 2022",  "These are a collection of Python projects I have made for my Python class in SJSU most of these are projects I have collaborated with. The GitHub repositories listed here may not contain the final code we used to turn in, as there were some syncing issues with our code. Some highlights of the class were using tkinter to make a matching game and a simple web server using django and flask.", new String[]{"https://github.com/CKhamis/CS-122-Homework-2", "https://github.com/CKhamis/CS-122-Homework-4", "https://github.com/CKhamis/CS-122-Homework-6", "https://github.com/CKhamis/CS-122-Homework-7", "https://github.com/CKhamis/CS-122-Homework-8"}));
        objects.add(new ProjectInfo("interdimensional", "java", "", "/images/webpageImages/CostiOnline.jpg", "Costi Online", false, "Personal Project | 2022", "Costi Online is a website that is designed to show off various projects, services, and media I made. This project initially began as a website that covers my 9th Minecraft survival world. It had links to participate in elections, polls, and the history of the previous worlds. After it was published on costionline.com, I decided to make it more general. The aforementioned feature has been moved to the <a href=\"/Minecraft\">Minecraft</a> section.", new String[]{"https://github.com/CKhamis/Costi-Online-Website"}));
        objects.add(new ProjectInfo("interdimensional", "java", "CIPolarium", "/images/webpageImages/Polarium.png", "Constantine [IN]GRID Polarium", true, "Personal Project | 2021", "This is a personal project I made that keeps track of various relationships I have made similar to a journal. I used Java Spring and Hibernate for this project, much like Costi Online. This project was discontinued because of complications with making a secure account system (which is very important for a personal journaling program). This program was able to add, edit, and remove people. Each person had their own database for tracking events.", new String[]{"https://github.com/CKhamis/Constantine-INGRID-Polarium"}));
        objects.add(new ProjectInfo("interdimensional", "java", "CNGrid", "/images/webpageImages/NextGrid.jpg", "Constantine [NEXT]GRID", true, "Private Repository | 2021", "This project was quite similar to [IN]GRID Polarium in terms of purpose. They both were designed to be a personal diary. However, this project used Java Swing as its interface and used CSV files for data persistence. There were no third party libraries used in this program, so I made my own CSV reader and writer classes myself. The project was discontinued due to frustrations with Java Swing and persistent bugs and limitations with displaying information. The GitHub repository is private because it contains a CSV file with personal information.", new String[]{}));
        objects.add(new ProjectInfo("interdimensional", "java", "", "/images/webpageImages/BankingApp.png", "Banking App", true, "School Collaborative Project | 2021", "\"Our banking app was created using the Java Swing library and an MVC pattern with event driven programming. The application allows for multiple users. Each user has their own account and have different bank accounts such as checkings and savings. The user is able to withdraw, deposit, and transfer to and from each account. In addition, the user has a Credit account where they can view thier credit card balance and pay off their credit card bill.\" - Sunny Chen, a collaborator", new String[]{"https://github.com/CKhamis/banking-app"}));
        objects.add(new ProjectInfo("pseudo-industrial", "java", "", "/images/webpageImages/SCQG.jpg", "Smart Console Query Generator", true, "Personal Project | 2020", "This project was made to help me automate a frequently repeating task of my job as an intern in the Cyber Security team of San Jose. This project was meant to create queries for the CheckPoint Smart Console application.", new String[]{"https://github.com/CKhamis/SmartConsoleQueryGenerator"}));
        objects.add(new ProjectInfo("pseudo-industrial", "java", "", "/images/webpageImages/Polaric.jpg", "Constantine [IN]GRID Polaric", true, "Private Repository | 2020", "This was an application designed to analyze spreadsheet journals. It could recognize different versions of the CSV files and show you differences between them, analyze the data in them so you can make better decisions, and more. It was quite an advanced program that took a few months to develop. The project was discontinued because I did not know how to make a GUI for it. This project contains personal information, so the repository is private.", new String[]{}));
        objects.add(new ProjectInfo("pseudo-industrial", "java", "", "/images/webpageImages/FGSA.jpg", "Five Guys Schedule Analyzer", true, "Personal Project | 2020", "This project was meant to take schedules I receive from Five Guys as an input and give me helpful analytical information. It used my CSV reader file to analyze each schedule and locate valuable information. Discontinued because I did not know of any good way of making a GUI.", new String[]{"https://github.com/CKhamis/Five-Guys-Schedule-Analyzer"}));
        objects.add(new ProjectInfo("pseudo-industrial", "web", "CIPolaris", "/images/webpageImages/Polaris.jpg", "Constantine [IN]GRID Polaris", true, "Personal Project | 2019", "This project was mainly developed using Javascript D3.js to populate data on webpages from CSV files. The purpose of this program is quite similar to what came after it, which is to display journaling information. The project was discontinued because I could not figure out how I would turn this into a functioning server in the long run. There are no public repositories for this project because the CSV it uses contains personal information.", new String[]{}));
        objects.add(new ProjectInfo("pseudo-industrial", "web", "", "/images/webpageImages/CostiInc.jpg", "Costi Inc.", true, "Personal Project | 2018", "This project is a website I made in 2018 that shared a very similar purpose to this website. It featured the different projects and video channels I was posting to at the time. It utilized bootstrap and was hand coded by me.", new String[]{"https://github.com/CKhamis/Costi-Inc"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/CR.jpg", "Costi Resume", true, "Personal Project | 2017", "Codename project Velocity. This is a resume website I made using HTML, CSS, and JavaScript. I was about 15 or 16 when I made this. I made this during the time I was learning D3.js", new String[]{"https://github.com/CKhamis/Resume-Website"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/InfiniteID.jpg", "Constantine Infinite ID", true, "Personal Project | 2017", "This was the first diary/journaling program I created for myself. It was a website that used D3.JS to pull information from a CSV file that contained all the information needed. The project was discontinued due to bugs that I could not remove at the time.", new String[]{"https://github.com/CKhamis/Infinite-ID"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/RoboticsWebsite3.png", "Pioneer Robotics Team Website (Milestone 3)", true, "Club Project | 2017", "This was a new project I wanted to make for my robotics team. I built it from scratch and I wanted to avoid the design misdirections its predecessors have taken (because of my team manager's preferences) while also applying feedback I heard about the current website. This website is unfinished because during its initial development, my team's manager suggested I should use a website builder instead. Knowing the countless hours and energy I put into this project (and previous robotics webpages) I quit.", new String[]{"https://github.com/CKhamis/https-github.com-CKhamis-Robotics-Website-Milestone-3"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/RoboticsWebsite2.png", "Pioneer Robotics Team Website (Milestone 2)", true, "Club Project | 2017", "This was an iteration of the previous milestone 1 robotics page. It had more features, simpler and easier to navigate pages, and more Java Script integration. It even featured the game snake on the 404 page. It was seemingly generally liked among my team.", new String[]{"https://github.com/CKhamis/Robotics-Website-Milestone-2"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/RoboticsWebsite.jpg", "Pioneer Robotics Team Website (Milestone 1)", true, "Club Project | 2016", "After making a handful of websites for my robotics team (each being rejected at their final development stages) I decided to have the team manager chose what elements he wanted in the team website. He ended up choosing this website design, which was not great in my personal opinion, but I was able to get this published. I made all the assets that went into this website and hand coded everything.", new String[]{"https://github.com/CKhamis/Resume-Website"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/Acceleration.png", "Pioneer Robotics Team Website (Codename: Acceleration)", true, "Club Project | 2015", "This was a website I made over the summer 2015 break in my freshman year. I created a colorful, eye-catching website for my robotics team. I made it entirely from HTML and CSS, created my own assets, and designed the layout myself. I do not have a backup of this project unfortunately and this screenshot is all I have of it. This project was promptly rejected during the first week of school.", new String[]{}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/MWC.jpg", "Pioneer Robotics Team Mobile Website C", true, "Club Project | 2015", "At the time, I was very proud of what I have made. I created a more consistent interface, invented the idea of team skill \"categories,\" with their own individual informative webpages, and displayed all information on our desktop website in a mobile friendly way. This was before I learned bootstrap well. This is not the final version of the project, as I distinctly remember placing JavaScript Easter eggs which are not present in the version I uploaded.", new String[]{"https://github.com/CKhamis/Robotics-Mobile-Website-C"}));
        objects.add(new ProjectInfo("highschool", "web", "", "/images/webpageImages/RoboticsMobileWebsite.jpg", "Pioneer Robotics Team Mobile Website", true, "Club Project | 2015", "When I joined my high school robotics team, I was asked by my web captain to create a mobile counterpart to our desktop only site. I eventually came up with this project. It featured javascript easter eggs and phone-specific styling. I used only HTML, CSS, and Java Script to create my project without any frameworks. The version pictured and saved to GitHub is a very early version of the project. I had since made other versions that look completely different.", new String[]{"https://github.com/CKhamis/Robotics-Mobile-Website"}));
        objects.add(new ProjectInfo("childhood", "web", "", "/images/webpageImages/Birds.jpg", "Original Angry Birds Wiki", true, "Personal Project | 2014", "This project is a website dedicated to the topic of Angry Birds, a game I liked when I was little. I hand coded this entire website using HTML and CSS with no frameworks.", new String[]{"https://github.com/CKhamis/Angrybird-Wiki"}));
        objects.add(new ProjectInfo("childhood", "web", "", "/images/webpageImages/OriginalCostiWebsite.jpg", "Original Laptoop Website", true, "Personal Project | 2013", "I made this website when I was first learning web development in 2013. At the time, I was 12. This website featured a product page for a made up laptop of the made up brand \"laptoop,\" which I came up with in third grade.", new String[]{"https://github.com/CKhamis/Laptoop-Company-Website"}));
        return objects;
    }

    public static List<MediaInfo> initializeMedia(){
        List<MediaInfo> media = new ArrayList<>();

        // 2022
        media.add(new MediaInfo("2022", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/LYXEK4cTHag\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>", "Flea Market Finds: Episode 2", "Adobe Premiere Pro | 2022", "Join Alex, Costi, Jack & Haydon in gathering the highest quality of finds at Capitol flea market! Although not perfect, this video uses enhanced editing techniques over the previous installment in the series.", "https://youtu.be/LYXEK4cTHag"));
        media.add(new MediaInfo("2022", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/5c5guItHIc4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>", "Flea Market Finds: Episode 1", "Adobe Premiere Pro | 2022", "Flea Market finds is the newest video series in my collection. Flea market finds is about what Haydon, me, and sometimes a special guest, find in flea markets. We both aim to collect electronics at cheap prices. In this episode, we go to Flea Market Capitol.", "https://youtu.be/5c5guItHIc4"));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV RH.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Rose Herrera\">", "JK CS Testimonial Video: Rose Herrera", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video completely by myself at Rose Herrera's house. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV CM.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Carol Marques\">", "JK CS Testimonial Video: Carol Marques", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent the raw version of this video, so I only participated in editing. I made sure to use practical and clear animations. I as asked to make this video in a landscape orientation, so I added filled the background with a blurry and enlarged version of the original video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV FT.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Fred Tovar\">", "JK CS Testimonial Video: Fred Tovar", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent the raw version of this video, so I only participated in editing. I made sure to use practical and clear animations. I as asked to make this video in a landscape orientation, so I added filled the background with a blurry and enlarged version of the original video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV RH O.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Rose Herrera\">", "JK CS Testimonial Video: Rose Herrera (Original)", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent the raw version of this video, so I only participated in editing. I made sure to use practical and clear animations. I as asked to make this video in a landscape orientation, so I added filled the background with a blurry and enlarged version of the original video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV JM.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: John McKay\">", "JK CS Testimonial Video: John McKay", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video myself at a major supporters' event. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV ML.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Marby Lee\">", "JK CS Testimonial Video: Marby Lee", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video myself at a major supporters' event. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV KJ.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Kevin Jensen\">", "JK CS Testimonial Video: Kevin Jensen", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video myself at a major supporters' event. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV MW.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Mike Wasserman\">", "JK CS Testimonial Video: Mike Wasserman", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I filmed and edited this video myself at a major supporters' event. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JK CS Ad 2.jpg\" class=\"card-img-top\" alt=\"Johnny Khamis for County Supervisor Ad 2\">", "Johnny Khamis for County Supervisor Ad 2", "Adobe Premiere Pro | 2022", "At my dad's campaign supporters' party, I filmed a short video ad featuring him. I made sure to use my new audio equipment to better capture his voice over the background noise. I also reused some assets from previous videos, as their purposes were very similar.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV PF.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Pam Foley\">", "JK CS Testimonial Video: Pam Foley", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video, and I was asked to handle all the editing for it. I made sure to use practical and clear animations. I as asked to make this video in a landscape orientation, so I added filled the background with a blurry and enlarged version of the original video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV TH.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Tim Herlihy\">", "JK CS Testimonial Video: Tim Herlihy", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video and I was asked to handle all the editing for it. I made sure to use practical and clear animations.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV SS.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Scot Smithee\">", "JK CS Testimonial Video: Scot Smithee", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video and I was asked to handle all the editing for it. I made sure to use practical and clear animations. At this point, I continued using the same assets I have created with the first video", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV TN.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Tam Nguyen\">", "JK CS Testimonial Video: Tam Nguyen", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video and I was asked to handle all the editing for it. I made sure to use practical and clear animations. I was also asked to provide English subtitles for the video, which I included as well.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV LD.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Lan Diep\">", "JK CS Testimonial Video: Lan Diep", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. I was sent a raw clip of this video and I was asked to handle all the editing for it. I made sure to use practical and clear animations. I was also asked to provide English subtitles for the video, which I included as well.\n", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV LM.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor YouTube Short Ad 2\">", "JK County Supervisor YouTube Short Ad 2", "Adobe Premiere Pro | 2022", "This was a video edited by myself and filmed by a third party that was shortened down as much as possible to fit into a YouTube 6-second ad. This video was shot in portrait, so I modified all my existing assets to work with it.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV NS.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor YouTube Short Ad 1\">", "JK County Supervisor YouTube Short Ad 1", "Adobe Premiere Pro | 2022", "This was a video edited by myself and filmed by a third party that was shortened down as much as possible to fit into a YouTube 6-second ad. This video was shot in portrait, so I modified all my existing assets to work with it.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV BH.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Bill Hubka\">", "JK CS Testimonial Video: Bill Hubka", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV LL.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Liz Lawler\">", "JK CS Testimonial Video: Liz Lawler", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV LC.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Larry Carr\">", "JK CS Testimonial Video: Larry Carr", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV DD.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Dev Davis\">", "JK CS Testimonial Video: Dev Davis", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV SL.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Sam Liccardo\">", "JK CS Testimonial Video: Sam Liccardo", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV MB.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Marie Blankley\">", "JK CS Testimonial Video: Marie Blankley", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV DG.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Don Gage\">", "JK CS Testimonial Video: Don Gage", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV DD.jpg\" class=\"card-img-top\" alt=\"JK CS Testimonial Video: Dev Davis\">", "JK CS Testimonial Video: Dev Davis", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS TV DK.jpg\" class=\"card-img-top\" alt=\"Dave Knopf\">", "JK CS Testimonial Video: Dave Knopf", "Adobe Premiere Pro | 2022", "For my dad's political campaign, I was tasked with making testimonial videos with as many of his supporters as possible for their advertising campaign. This is one of several videos I was asked to modify slightly in the same way as the original ad.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Homelessness.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor Homelessness Ad\">", "JK County Supervisor Homelessness Ad", "Adobe Premiere Pro | 2022", "This was the first video ad I created myself for my dad's political campaign. We used my dad's phone to film this video because of its portability. Since the video was filmed in the same spot as the previous, my editing techniques did not change.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Safety.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor Safety Ad\">", "JK County Supervisor Safety Ad", "Adobe Premiere Pro | 2022", "This was the first video ad I created myself for my dad's political campaign. We used my dad's phone to film this video because of its portability. This video was about safety in the county. I needed to use my video editing skills to quicken the video.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Parks.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor Parks Ad\">", "JK County Supervisor Parks Ad", "Adobe Premiere Pro | 2022", "This was the first video ad I created myself for my dad's political campaign. We used my dad's phone to film this video because of its portability. This video was about protecting the environment and open spaces in the county. Heavy noise reduction was needed because it was windy", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Lightrail.jpg\" class=\"card-img-top\" alt=\"JK County Supervisor Lightrail Ad\">", "JK County Supervisor Lightrail Ad", "Adobe Premiere Pro | 2022", "This was the first video ad I created myself for my dad's political campaign. We used my dad's phone to film this video because of its portability. I used my skills in video editing to remove audio noise, stabilize the video, add effects, and display the logo.", ""));
        media.add(new MediaInfo("2022", "", "live-action", "<img src=\"/images/webpageImages/JKCS Ad 1.jpg\" class=\"card-img-top\" alt=\"Johnny Khamis County Supervisor Commercial 1\">", "Johnny Khamis County Supervisor Commercial 1", "Adobe Premiere Pro | 2022", "This was a video that I was asked to modify that was originally created by a hired third party. I was asked to edit some text, add the logo, and other small fixes.", ""));

        //2021
        media.add(new MediaInfo("2021", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/xpnTFsiiA_0\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Memory Slideshow: Summer 2021", "Adobe Premiere Pro | 2021", "As the title suggests, this is a montage of the best memories I had in my summer 2021. This isn't the first video in the memory montage series, and certainly not the last. Although there is not enough Minecraft here!", ""));

        //2020
        media.add(new MediaInfo("2020", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/OlB1ILARBxE\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Memory Slideshow: SJSU 2019", "Adobe Premiere Pro | 2020", "This video highlighted my first semester and a half at SJSU. The selfies I took were part of a school project, so don't judge \uD83D\uDE24", "https://youtu.be/OlB1ILARBxE"));
        media.add(new MediaInfo("2020", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/jDfV5RQrKlU\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Memory Slideshow: Summer 2019", "Adobe Premiere Pro | 2020", "This is the second memory montage in the series about my summer in 2019", "https://youtu.be/jDfV5RQrKlU"));
        media.add(new MediaInfo("2020", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/Oc8686Xw7vg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Memory Slideshow: Pioneer 2019", "Adobe Premiere Pro | 2020", "Bored and stuck at home with nothing to film, I decided to begin a series of compilations that would help me remember the good times. This was the first in the series. It was about my time in high school.", "https://youtu.be/Oc8686Xw7vg"));
        media.add(new MediaInfo("2020", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/blxsL72ZpT4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "PPAP", "Adobe Premiere Pro | 2020", "Filmed in 2016, this video was a parody of the infamous PPAP video that was popular at the time. This project was never edited because I thought it was cringy at the time, which was exactly why I edited it in 2020. This is the last Costi Entertainment branded video. The editing used here is far better than what I made in 2016, which is a good indicator of the progression of my skill.", "https://youtu.be/blxsL72ZpT4"));
        media.add(new MediaInfo("2020", "", "animation", "<iframe src=\"https://www.youtube-nocookie.com/embed/phRo1lOsNts\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Costi Entertainment Intro 2020", "Adobe Premiere Pro | 2020", "This was the last Costi Entertainment intro I made. Not knowing what was going to happen next, I had big plans for 2020. I made this intro video, but it was only used in 1 video.", "https://youtu.be/phRo1lOsNts"));

        //2019
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/Z_UgFKMnqXc\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Pioneer News Episode 9", "Adobe Premiere Pro & Adobe After Effects | 2019", "This was a short video I was asked to make for our school's farewell rally. It featured the anchors that will be in the next year's news.", "https://youtu.be/Z_UgFKMnqXc"));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/NV3L8fhayhg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Pioneer News Episode 8: Finale", "Adobe Premiere Pro & Adobe After Effects | 2019", "This was the very last episode of the Pioneer news. I wanted to make it extra special. I added in new elements, styled the transitions and other elements to promote the yearbook, added a special iCarly intro, a tribute to the multimedia class we had (I was not the person filming), and finally, the Pioneer Montage. The Pioneer Montage was a collection of student-submitted videos edited with music and special effects. It was meant to be my last goodbye to my school.", "https://youtu.be/NV3L8fhayhg"));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/ZFzfAfLXp1E\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Pioneer News Episode 7", "Adobe Premiere Pro & Adobe After Effects | 2019", "In this episode, I added new flouts, a new outro, and refined a lot of elements in the news. I feel at this point, my skills in Adobe After Effects and Adobe Premiere Pro were advanced.", "https://youtu.be/ZFzfAfLXp1E"));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/ROLHtUkPwU4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Toxic Restoration", "Adobe Premiere Pro | 2019", "This is a school project I made on a team, directed by Devin McKiernan. Two teenage brothers attempt to escape their hometown during the outbreak of a cure gone wrong, while the federals wipe out all living beings with the hope of restoring faith in humanity.", "https://youtu.be/ROLHtUkPwU4"));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/QA51mrB1fAE\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Pioneer News Episode 6", "Adobe Premiere Pro & Adobe After Effects | 2019", "In this episode, I made some enhancements ot the \"at a glance\" intro, finalized the top and bottom letter box panels, added an ad for a special segment I was going to air on the last episode, and updated the AP test information.", "https://youtu.be/QA51mrB1fAE"));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/E5niprbIE6E\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Pioneer News Episode 5", "Adobe Premiere Pro & Adobe After Effects | 2019", "This episode took a lot of effort for me. I further refined the top and bottom letter boxing panels, I re-did the intro, added in different background music (suggested by Ryan), tweaked a lot of the special effects, added in a stressful countdown to the next AP test that was timed specifically to be accurate when it aired, added an \"at a glance\" intro, and made a special part on the end that served as an overview of the upcoming AP tests (some thought that the images used were official, but I made them).", "https://youtu.be/E5niprbIE6E"));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/yzEc6DrS4Ug\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Pioneer News Episode 4", "Adobe Premiere Pro & Adobe After Effects | 2019", "In this episode, I began editing episodes with the cooperation of my good friend Ryan Zimbauer. He helped me with editing the leadership videos that would come in and the moving background. Cory Robertson, another close friend, helped me film the drone footage for the new intro. I also added refinements to the aforementioned elements on the top and bottom.", "https://youtu.be/yzEc6DrS4Ug"));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/JNaSQrSj6XQ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>v", "Pioneer News Episode 3", "Adobe Premiere Pro & Adobe After Effects | 2019", "In this episode, I refined a lot of the features I added in the 2nd video. I also added in a cool intro using Leland's school news intro music. I was also able to experiment a lot more with nesting sequences in After Effects.", "https://youtu.be/JNaSQrSj6XQ"));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/BuvJfhaYiKk\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Pioneer News Episode 2", "Adobe Premiere Pro & Adobe After Effects | 2019", "Although this is not the second episode of the Pioneer News ever, it was the second episode I edited. Near the middle of my last semester of high school, my multimedia teacher could not find any more people to edit the news. I decided to step up and handle editing from then on. In this episode, I learned from the previous episode I made and added some new features. For example, I knew that the projectors in school were 4:3, so I decided to use lettering to add in an agenda and additional information panels. Also, I dabbed at the end \uD83D\uDC80", "https://youtu.be/BuvJfhaYiKk"));
        media.add(new MediaInfo("2019", "", "live-action", "<img src=\"/images/webpageImages/Ethan Projects.jpg\" class=\"card-img-top\" alt=\"Ethan Projects\">", "Ethan's School Projects", "Adobe Premiere Pro | 2019", "In 2019, Ethan asked me to help him edit two of his school projects, one of them was a shorter video for his Spanish class called En El Restaraunte and the other was a parody of Romeo and Juliet, except as a modern reality T.V show.", ""));
        media.add(new MediaInfo("2019", "", "flyer", "<img src=\"/images/webpageImages/State Senate.jpg\" class=\"card-img-top\" alt=\"State Senate\">", "Johnny Khamis State Senate Graphics", "Adobe Illustrator | 2019", "In 2019, I helped out my dad with his political campaign for State Senate. Apart from helping with the website, I also made many graphics for the campaign (not the logo) including social media banners, letterheads, and fundraising flyers. I used Adobe Illustrator to create and edit the graphics on each of these flyers", ""));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/87UCkLWjtcc\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "How to Remove a Tree in San Jose", "Adobe Premiere Pro | 2019", "This is a video that my friends and I made for my San Jose Tips club at school. It took a lot of research, coordination, and filming. Although the production of this video was fun, it ultimately lacked focus and professionalism the other videos did. For this reason, I removed it for the public to see from the main YouTube channel. It is still available to view here.", "https://youtu.be/87UCkLWjtcc"));
        media.add(new MediaInfo("2019", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/J2UbqFYrEsk\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "San Jose Tips School Ad", "Microsoft Video Editor & Adobe After Effects | 2019", "In the beginning of 2019, I was tasked with making an ad for my school news. Since I had my own club already, I decided to make an ad for it. I tried to make it as concise and clear as possible so viewers would join. I also tried using the new Microsoft Video Editor which worked well for this kind of video.", "https://youtu.be/J2UbqFYrEsk"));

        //2018
        media.add(new MediaInfo("2018", "", "logo", "<img src=\"/images/webpageImages/Logo5.jpg\" class=\"card-img-top\" alt=\"logo 5\">", "Costi Logo 5", "Adobe Illustrator | 2018", "My logo was re-designed in 2018 to make it nicer on the eyes. The individual squares are larger and closer together. Previously, the gap between each square was the same as their length. Now, they are spaced out by the width of the \"E\" in the old Costi entertainment logo. This version of my logo is still used today, and can be found even on the footer of this page.", ""));
        media.add(new MediaInfo("2018", "", "animation", "<img src=\"/images/webpageImages/Judge.jpg\" class=\"card-img-top\" alt=\"Judge Kaylynn\">", "Judge Kaylynn", "Adobe Premiere Pro | 2018", "I made this short intro video for my government class presentation. The video editing itself was very polished and practical. It featured a slow motion scene of my project partner hitting an apple in slow motion.", ""));
        media.add(new MediaInfo("2018", "", "live-action", "<img src=\"/images/webpageImages/Pioneer News 1.jpg\" class=\"card-img-top\" alt=\"Pioneer News 1\">", "Pioneer News Episode 1", "Adobe Premiere Pro | 2018", "In my multimedia class, every student was tasked with making a weekly episode of the school news at least once a semester whether you liked it or not. In this case, I did not want to edit the news, and although I added some cool new ideas like transitions, I did not put too much effort into it. Unfortunately, I have lost all the files and the original link to this video, so it is lost forever.", ""));
        media.add(new MediaInfo("2018", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/rwqnHULVyeE\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "San Jose Tips Animated Intro", "Adobe Premiere Pro | 2018", "In order to prepare for a new YouTube video my team was making, I made an animated intro that would be used in our videos. This was made in Adobe After Effects, which I was still getting used to using at the time.", "https://youtu.be/rwqnHULVyeE"));
        media.add(new MediaInfo("2018", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/GntpB0jWT3k\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Creeper Trauma", "Adobe Premiere Pro | 2018", "This is another video I made for school. The assignment was to make an interview. It could be about anything. For my project, I made a video interviewing Alex about a creeper explosion in Minecraft.", "https://youtu.be/GntpB0jWT3k"));
        media.add(new MediaInfo("2018", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/du8uTwbE4_0\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "My San Jose Episode 5 - Potholes", "Adobe Premiere Pro | 2018", "This 5th and final video in the series concerns reporting potholes in San Jose using the My San Jose app. In this episode, we used Kristi's ukelele to make original background music. Councilmember Chappie Jokes was featured in this episode.", "https://youtu.be/du8uTwbE4_0"));
        media.add(new MediaInfo("2018", "", "live-action", "<img src=\"/images/webpageImages/Sp2.jpg\" class=\"card-img-top\" alt=\"Spanish Video 2\">", "Spanish Video 2", "Adobe Premiere Pro | 2018", "This was a music parody video about congugating verbs in Spanish. The song we used was All Stars, and it was met with positive feedback, even from the teacher. This video is unavailable to show because it features personal information.", ""));
        media.add(new MediaInfo("2018", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/_Msk2fH7NXM\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "My San Jose Episode 4 - Illegal Dumping", "Adobe Premiere Pro | 2018", "The next episode in the My San Jose series is how to report illegal dumping. This episode in particular featured former council member Lan Diep.", "https://youtu.be/_Msk2fH7NXM"));
        media.add(new MediaInfo("2018", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/jC4J4U9z0qQ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "My San Jose Episode 3 - Abandoned Vehicles", "Adobe Premiere Pro | 2018", "Continuing the My San Jose series on the San Jose Tips YouTube Channel, I created a video demonstrating how to get rid of abandoned vehicles. This video featured former city council member Raul Paralez.", "https://youtu.be/jC4J4U9z0qQ"));
        media.add(new MediaInfo("2018", "", "live-action", "<img src=\"/images/webpageImages/Ethan Show E3.jpg\" class=\"card-img-top\" alt=\"The Ethan Show Episode 2 Re-Edit\">", "The Ethan Show: Episode 3", "Adobe Premiere Pro | 2018", "                                The Ethan Show Episode 3 was built using the feedback we received from the previous episode. We added more segments, used different kinds of jokes, and had more planned videos. This video was met with better reception, but it failed to capture the audience who disliked the second episode. I used advanced layering techniques for this video. Unfortunately, this is the last episode of the Ethan Show that was fully finished.", ""));
        media.add(new MediaInfo("2018", "", "live-action", "<img src=\"/images/webpageImages/Ethan Show E2 R.jpg\" class=\"card-img-top\" alt=\"The Ethan Show Episode 2 Re-Edit\">", "The Ethan Show: Episode 2 Re Edit", "Adobe Premiere Pro | 2018", "                                Following the reception of second episode, I decided to shorten certain segments of the show to make it more watchable. The original version of this episode was over 23 mins! This new version is 16 mins. It has better editing, smoother green screen effects, and more.", ""));
        media.add(new MediaInfo("2018", "", "animation", "<iframe src=\"https://www.youtube-nocookie.com/embed/D_Fdq-GZJyc\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Costi Entertainment 2018 Logo", "Adobe Premiere Pro | 2018", "                                For 2018, I wanted to make my intro a little more dynamic. I did this by incorporating a lot more moving elements such as the text moving and the individual squares. I also made them come together to form my logo in the end, a nod to my original animated logo.", "https://youtu.be/D_Fdq-GZJyc"));

        //2017
        media.add(new MediaInfo("2017", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/Ldg8wVFHTtU\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "My San Jose Episode 2 - How to Report Graffiti", "Adobe Premiere Pro | 2017", "                                This was the second San Jose Tips video in the series, where Kristi will show you how to report graffiti via the My San Jose app. We even had council member Dev Davis featured on this video!", "https://youtu.be/Ldg8wVFHTtU"));
        media.add(new MediaInfo("2017", "", "animation", "<img src=\"/images/webpageImages/ASAS 17.5.jpg\" class=\"card-img-top\" alt=\"ASAS 2017.5 project\">", "ASAS 17.5 Invitation Video", "Adobe Premiere Pro | 2017", "This is the final video in my ASAS invitation series. This video is by far the most ambitious video I made, as it has both live videos and animations. I stopped making invitational videos because the medium was too limiting and most of the hard work that went into them went unappreciated.", ""));
        media.add(new MediaInfo("2017", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/tbVGsahOHhs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Dora and the Quest to Find the Preterite", "Adobe Premiere Pro | 2017", "                                This was an interesting video some friends, and I made for a Spanish project. The main character Dora and his assistant boots embark on a journey to find the preterite himself. The ending of the video contains Spanish worksheet information, which was a required element.", "https://youtu.be/tbVGsahOHhs"));
        media.add(new MediaInfo("2017", "", "live-action", "<img src=\"/images/webpageImages/Eng2.jpg\" class=\"card-img-top\" alt=\"English Project\">", "Prohibition Video", "Adobe Premiere Pro | 2017", "                                This was a video created for my English class to address the US prohibition. Although it wasn't a revolutionary video, it did give me more experience working with actors that aren't my usual ones.", ""));
        media.add(new MediaInfo("2017", "", "live-action", "<img src=\"/images/webpageImages/Ethan Show E2.jpg\" class=\"card-img-top\" alt=\"The Ethan Show Episode 2\">", "The Ethan Show: Episode 2", "Adobe Premiere Pro | 2017", "                                The Ethan Show Episode 2 solidified the show's wacky formula of having spontaneous humor, strange situations, and video segments. This video was posted to YouTube and was met with a mixed reception. Nevertheless, Ethan and I continued making videos.", ""));
        media.add(new MediaInfo("2017", "", "live-action", "<img src=\"/images/webpageImages/Ethan Show E1.jpg\" class=\"card-img-top\" alt=\"The Ethan Show\">", "The Ethan Show", "Adobe Premiere Pro | 2018", "                                The Ethan Show is a silly video that has a similar style to Amal+. They were similar in how both of them were segmented videos, but they differ in how the segments are somewhat related to each other. The Ethan Show went on to have 2 more episodes and an unfinished 4th episode. Unfortunately, I will not be having the first episode available to the public.", ""));
        media.add(new MediaInfo("2017", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/r1eit2lMt6s\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "My San Jose Episode 1 - How to Report a Broken Streetlight", "Adobe Premiere Pro | 2017", "                                The My San Jose series of videos were meant to show citizens of San Jose how to use the various services available to them. In this episode, Kristi will show you how to report a broken street light on the My San Jose app. This video idea was met with praise among the city council, and caught the interest of San Jose mayor San Liccardo, who was featured in the intro of this episode.", "https://youtu.be/r1eit2lMt6s"));
        media.add(new MediaInfo("2017", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/Ltu5JuV7Cww\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Don't be a Bully", "Adobe Premiere Pro | 2017", "                                In this short PSA, Amal learns that a mysterious stranger is in fact, a bomb that blows her up. The lesson learned? Don't be a bully!", "https://youtu.be/O2FpzlorcqI"));
        media.add(new MediaInfo("2017", "", "animation", "<iframe src=\"https://www.youtube-nocookie.com/embed/t1rAfLk2ZOM\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Costi Entertainment 2017 Logo", "Adobe Premiere Pro | 2018", "                                This was the newest intro logo video I made at the time. I wanted it to have a bolder appearance, so I tried to use less grey colors. At the end of the video, I had a colorful display with the year on the top left. I feel like this is a clear example of my progression of skill in After Effects.", "https://youtu.be/t1rAfLk2ZOM"));
        media.add(new MediaInfo("2017", "", "animation", "<img src=\"/images/webpageImages/ASAS 17.jpg\" class=\"card-img-top\" alt=\"ASAS 17\">", "ASAS 17 Invitation", "Adobe Premiere Pro | 2017", "                                This is an invitational video I created for my ASAS party in the beginning half of 2017. This video featured much smoother animations and more fitting music. The project used assets form previous videos in the series, which made the creation of the video a lot quicker.", ""));

        //2016
        media.add(new MediaInfo("2016", "", "animation", "<img src=\"/images/webpageImages/ASAS 16.5.jpg\" class=\"card-img-top\" alt=\"ASAS 16.5\">", "ASAS 16.5 Invitation", "Adobe Premiere Pro | 2016", "                                This is a video I created for ASAS 16.5, which was a party hosted after school during winter break. These videos were meant to promote the parties themselves and get people excited to attend. This is the first video to feature live shots of various items in my house as b-roll. I continued to use video invitations for my ASAS parties until December of 2017.", ""));
        media.add(new MediaInfo("2016", "", "live-action", "<img src=\"/images/webpageImages/ALT.jpg\" class=\"card-img-top\" alt=\"Alex Lacks Talent\">", "Alex Lacks Talent (Game Show)", "Adobe Premiere Pro | 2016", "                                Alex Lacks Talent is a game show Amal, Taleen, Tina, and I invented. In this game-show, 6 contestants (2 clones of Alex, Amal, and Tina) would compete against each other for an unspecified prize. Taleen made her first appearance in my videos as the host of the gameshow. In the beginning of the video, we meet the contestants, then we see their backstories, and finally, we see their talent (after a commercial break). This video is unavailable to watch because it contains some personal information.", ""));
        media.add(new MediaInfo("2016", "", "live-action", "<img src=\"/images/webpageImages/Votes.jpg\" class=\"card-img-top\" alt=\"Votes\">", "Votes", "Adobe Premiere Pro | 2016", "                                In this silly video, viewers are asked to vote for one of two contestants: Amal or Tina. Lots of chaotic things happen in this video which adds to its humor. Although I did not learn any new skills from this video, it was the first time I turned off a green screen effect within a video on purpose.", ""));
        media.add(new MediaInfo("2016", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/L6iCCy-I4Qs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Internet Trailer Re Edit", "Adobe Premiere Pro | 2016", "                                This is a re-edit plus a remake of the original Internet Trailer video I made the year before. This time, I changed the music, added in hints at corruption, and used slightly better effects.", "https://youtu.be/L6iCCy-I4Qs"));
        media.add(new MediaInfo("2016", "", "live-action", "<img src=\"/images/webpageImages/Pacer.jpg\" class=\"card-img-top\" alt=\"Costi Logo 4\">", "Pacer Test Music Video", "Adobe Premiere Pro | 2016", "                                This video is a wacky music video for the pacer test audio used in our schools. It features 3 Alex clones. The left one is supposed to be playing an instrument, but keeps getting texts on his phone; the center Alex is the \"singer\"; and the Alex on the right is incorrectly playing a recorder. The video skips around the test in strange ways.", ""));
        media.add(new MediaInfo("2016", "", "animation", "<img src=\"/images/webpageImages/ASAS 16 U1.jpg\" class=\"card-img-top\" alt=\"ASAS 16 U1\">", "ASAS 16 Invitation Update", "Adobe Premiere Pro | 2016", "                                This is a short invitational update video in regard to ASAS 16. It was created just 2 days after the original video was sent out so I can showcase the updated invitation roster.", ""));
        media.add(new MediaInfo("2016", "", "animation", "<img src=\"/images/webpageImages/ASAS 16.jpg\" class=\"card-img-top\" alt=\"ASAS 16\">", "ASAS 16 Invitation", "Adobe Premiere Pro | 2016", "                                This is the first invitational video I created for my after school parties, also known as ASAS. I created these videos to create excitement around my parties. This video was one of the first After Effects projects I made.", ""));
        media.add(new MediaInfo("2016", "", "live-action", "<img src=\"/images/webpageImages/Flash Drive.jpg\" class=\"card-img-top\" alt=\"Flash Drive\">", "Princess of Sale's Flash Drive Ad", "Adobe Premiere Pro | 2016", "                                In this video, the self-proclaimed Princess of Sale tries to sell you a flash drive she doesn't want to anymore. This video a green screen effect and also a part where it appears she is throwing Terence at the camera. I did this by keying the positioning and scale of an image of Terence by hand.", ""));
        media.add(new MediaInfo("2016", "", "live-action", "<img src=\"/images/webpageImages/Just Dance.jpg\" class=\"card-img-top\" alt=\"Just Dance\">", "Just Dance 2014 Commercial", "Adobe Premiere Pro | 2016", "                                Amal and Tina asked me to make a video showcasing their favorite game at the time, Just Dance 2014. In this video, Amal shows you how to open Just Dance, selecting a song, and dancing. I also tried changing some text on the video with special effects via After Effects.", ""));
        media.add(new MediaInfo("2016", "", "live-action", "<iframe src=\"https://www.youtube-nocookie.com/embed/G_1K5mB3bVY\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Scary Scene 1", "Adobe Premiere Pro | 2016", "                            This video was made out of boredom when I was stuck in my house. I wanted to venture and try out a genre I haven't tried making before: horror. Having watched all the Harry Potter movies, I took inspiration from their cinematography and created this video. For what it was, I think it came out pretty well. Additionally, the end of the video is advertising a very short-lived rebrand of my video production alias to Costi T.V.", "https://youtu.be/G_1K5mB3bVY"));
        media.add(new MediaInfo("2016", "", "animation", "<iframe src=\"https://www.youtube-nocookie.com/embed/8I9CEoZc91U\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>", "Costi Entertainment 2016 Logo", "Adobe Premiere Pro | 2016", "                                Costi Entertainment was the new alias I used for video production. Like the previous year, this intro video was featured before or during each non-school video project I made. This solidified an annual tradition for me, as I would always make a new intro every year.", "https://youtu.be/XH2DNsJX8Pk"));
        media.add(new MediaInfo("2016", "", "logo", "<img src=\"/images/webpageImages/Logo4.jpg\" class=\"card-img-top\" alt=\"Costi Logo 4\">", "Costi Logo 4", "Adobe Illustrator | 2016", "                                This is what I called the 4th iteration of my logo. The first version was shown below and was off center, the second was the orb version, and the third was the same as the first version except grey and tilted 45 degrees. This logo is important to me because it was used in many, many projects once it was made. This is because the image did not have any blank padding on the sides and was perfectly centered.", ""));

        //2015
        media.add(new MediaInfo("2016", "", "live-action", "<img src=\"/images/webpageImages/Ethan Show E3.jpg\" class=\"card-img-top\" alt=\"The Ethan Show Episode 2 Re-Edit\">", "The Ethan Show: Episode 3", "Adobe Premiere Pro | 2018", "", ""));

        return media;
    }
}
